name: Build & deploy

on:
  workflow_run:
    workflows:
      - Mocha
    types:
      - completed
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*'
  push:
    branches:
      - main
    paths:
      - 'src/**/*'

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build & Deploy

    runs-on: ubuntu-latest
    timeout-minutes: 10

    if: ${{ github.repository != 'conqueror-site-builder/conqueror' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: package-lock.json
          cache: npm
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
