name: Build & deploy

on:
  workflow_run:
    workflows:
      - Mocha
    types:
      - completed
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'src/**/*'

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.repository != 'conqueror-site-builder/conqueror'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
